name: ThonkingWildSpawn
author: Endermanbugzjfc
api: [3.0.0, 3.12.0, 3.13.0]
version: 1.2.0
main: Endermanbugzjfc\ThonkingWildSpawn\ThonkingWildSpawn
socials: NO ;-;

commands:
  wildspawn:
    permission: wildspawn.check
    aliases: 
      - randomspawn
      - randspawn

permissions:
  wildspawn:
    default: op
    children:
      wildspawn.check:
        description: Permission for checking wild spawn info
        default: op
      wildspawn.mod:
        description: Permission for modifying wild spawn settings
        default: op

#    ################    #
#    # @@@          #    #
#    #  @       @@@ #    #
#    #           @  #    #
#    #@@@  ####     #    #
#    #@@@@@@@@      #    #
#    #@@@@@@        #    #
#    ################    #